### ISSUE TITLE
シラバスデータの更新

### ISSUE THREAD

**Issue by eggplants** [Make-IT-TSUKUBA/alternative-tsukuba-kdb#5]
https://github.com/inaniwaudon/alternative-tsukuba-kdb/issues/14
> おそらく今後も運営するためには、シラバスデータの更新が必要です。
> 手間を考えると、手動更新よりGitHub ActionsなどのCIで定期的に自動更新するのが望ましいです。

KdBが再開次第対応したいですね。

**Comment by eggplants** [comment]
雑に書いた、CSVのダウンロードの後JSONに変換して諸々Commitするやつです。

```yml
name: CSV scheduled update

on:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sun
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install requests
      - name: Download CSV
        run: |
          cd .github && python download.py
          cd ..
      - name: Make JSON
        run: |
          python make-json/csv-json.py ".github/csv/kdb-$(date +%Y%m%d).csv" make-json/list.txt False
      - name: Commit
        run : |
              - name: Commit
      run: |
        git add .
        git commit -m "update: $(date +%Y%m%d)"
        git push origin master
```
